services:
  - type: web
    name: plateforme-services
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py makemigrations --dry-run && python manage.py migrate"
    startCommand: "gunicorn plateforme_services.wsgi:application"
    healthCheckPath: /admin/login/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plateforme-services-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_DEBUG
        value: "True"  # Temporaire pour voir les erreurs détaillées
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: PYTHONPATH
        value: "."
    autoDeploy: true

  - type: pserv
    name: plateforme-services-db
    plan: free
    databaseName: plateforme_services_db
    ipAllowList: []