# Generated by Django 5.1.5 on 2025-06-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_client_options_alter_provider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
